# Generated by Django 2.2 on 2019-04-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='email',
        ),
        migrations.RemoveField(
            model_name='listener',
            name='username',
        ),
    ]
